drop table img_board;

-----------------보드게시판--------------------------
CREATE TABLE BOARD 
(
  BOARD_IDX NUMBER(4, 0) NOT NULL 
, BOARD_NAME VARCHAR2(100 BYTE) NOT NULL 
, BOARD_TITLE VARCHAR2(100 BYTE) NOT NULL 
, BOARD_CONTENT VARCHAR2(300 BYTE) NOT NULL 
, BOARD_DATE DATE DEFAULT SYSDATE 
, BOARD_HIT NUMBER(4, 0) DEFAULT 0 
, FILENAME1 VARCHAR2(200 BYTE) 
, FILENAME2 VARCHAR2(200 BYTE) 
, FILENAME3 VARCHAR2(200 BYTE) 
, FILEPATH VARCHAR2(300 BYTE) 
, CONSTRAINT SYS_C007027 PRIMARY KEY 
  (
    BOARD_IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C007027 ON BOARD (BOARD_IDX ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

create sequence BOARD_IDX_seq;



--------------------------------------------------------------------------------


--이미지 게시판 쿼리문--
CREATE TABLE IMG_BOARD 
(
  IMG_BOARD_IDX NUMBER(8, 0) NOT NULL 
, IMG_BOARD_NAME VARCHAR2(100 BYTE) NOT NULL 
, IMG_BOARD_TITLE VARCHAR2(100 BYTE) NOT NULL 
, IMG_BOARD_CONTENT VARCHAR2(300 BYTE) NOT NULL 
, IMG_BOARD_FILENAME1 VARCHAR2(100 BYTE) NOT NULL 
, IMG_BOARD_FILENAME2 VARCHAR2(100 BYTE) 
, IMG_BOARD_FILENAME3 VARCHAR2(100 BYTE) 
, IMG_BOARD_FILEPATH VARCHAR2(200 BYTE) NOT NULL 
, IMG_BOARD_DATE DATE NOT NULL 
, IMG_BOARD_RM NUMBER(8, 0) 
, IMG_BOARD_HIT NUMBER(8, 0) 
, IMG_BOARD_CATEGORY VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT IMG_BOARD_PK PRIMARY KEY 
  (
    IMG_BOARD_IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX IMG_BOARD_PK ON IMG_BOARD (IMG_BOARD_IDX ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

create sequence IMG_BOARD_IDX_seq;


-------------------------------------------------------------------------------------

--맴버테이블--
CREATE TABLE MEMBER 
(
  MEMBER_IDX NUMBER(4, 0) NOT NULL 
, MEMBER_ID VARCHAR2(100 BYTE) NOT NULL 
, MEMBER_PW VARCHAR2(100 BYTE) NOT NULL 
, MEMBER_EMAIL VARCHAR2(100 BYTE) NOT NULL 
, MEMBER_NAME VARCHAR2(100 BYTE) NOT NULL 
, MEMBER_JOINDATE DATE NOT NULL 
, CONSTRAINT MEMBER_PK PRIMARY KEY 
  (
    MEMBER_IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MEMBER_PK ON MEMBER (MEMBER_IDX ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

create sequence MEMBER_IDX_seq;

--------------------------------------------------------------------------


--댓글테이블--
CREATE TABLE REPLY 
(
  REPLY_IDX NUMBER(4, 0) NOT NULL 
, REPLY_NAME VARCHAR2(100 BYTE) NOT NULL 
, REPLY_CONTENT VARCHAR2(300 BYTE) NOT NULL 
, REPLY_DATE DATE NOT NULL 
, REPLY_BOARD_IDX NUMBER 
, REPLY_IMG_BOARD_IDX NUMBER 
, CONSTRAINT REPLY_PK PRIMARY KEY 
  (
    REPLY_IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REPLY_PK ON REPLY (REPLY_IDX ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

create sequence REPLY_IDX_seq;


